name: indiakart
description: "Indiakart: A hyper-local e-commerce and services app."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

# ... all other dependencies remain the same
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  #...etc

dev_dependencies:
  flutter_test:
    sdk: flutter
  #...etc

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sample_data/
