import 'package:indiakart/utils/theme.dart'; // Change this import if you rename the folder
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This file will be generated by the FlutterFire CLI
import 'package:indiakart/screens/main_navigation.dart'; // Change this import if you rename the folder

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // TODO: Run 'flutterfire configure' to generate firebase_options.dart
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const ProviderScope(child: IndiakartApp()));
}

class IndiakartApp extends StatelessWidget {
  const IndiakartApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Indiakart',
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: ThemeMode.system,
      debugShowCheckedModeBanner: false,
      home: const MainNavigation(),
    );
  }
}
